=== erikhaugen/web/livescribe/lstokenservice/src/test/resources/data/dtd/pen.dtd
<!ELEMENT dataset (pen*)>

<!ELEMENT pen EMPTY>
<!-- Must include 'pen_id' column to workaround 'bug' in DbUnit when
	 deleting DataSet records from database. -->
<!ATTLIST pen pen_id							CDATA #IMPLIED>
<!ATTLIST pen display_id						CDATA #IMPLIED>
<!ATTLIST pen serialnumber						CDATA #IMPLIED>
<!ATTLIST pen serialnumber_hex					CDATA #IMPLIED>
<!ATTLIST pen firmware_version					CDATA #IMPLIED>
<!ATTLIST pen pen_type							CDATA #IMPLIED>
<!ATTLIST pen pen_certificate_id				CDATA #IMPLIED>
<!ATTLIST pen pen_request_id					CDATA #IMPLIED>

<!ELEMENT pen_certificate EMPTY>
<!ATTLIST pen_certificate certificate_path		CDATA #IMPLIED>

<!ELEMENT pen_request EMPTY>
<!ATTLIST pen_request vendor_id					CDATA #IMPLIED>

=== erikhaugen/web/livescribe/lsregistration/src/test/resources/data/setup/pen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset SYSTEM "../dtd/pen.dtd">
<dataset>
	<pen display_id="AYE-AAA-ACE-8F" serialnumber="2594160246848" serialnumber_hex="25C00000040" firmware_version="1.4" pen_type="Pulse" created="2013-10-01 16:29:20" />
	<pen display_id="AYE-AAA-AE9-B3" serialnumber="2594160246933" serialnumber_hex="25C00000095" firmware_version="2.7" pen_type="Pulse" created="2013-10-01 16:29:20" />
	<pen display_id="QBX-018-XVR-QQ" serialnumber="7823948029286" serialnumber_hex="78A00000066" firmware_version="1.5" pen_type="Echo Wi-Fi" created="2013-10-01 16:29:20" />
	
	<pen display_id="AYE-ASW-ABK-EH" serialnumber="2594172882823" serialnumber_hex="25C00C0CF87" firmware_version="1.5" pen_type="Vector" key_transport="1766A10E39E5E6C270C57BBFF5DDD1A98950DC0FF881D8C57B213AA3EFDB8A2F26F2F31D0016402F49DF71AEE5EA4000D892306A608B82469ABF7A31AF394ABA0747F3D2CF387F22CE54D50AB56AEF685534065513772B2BBD236CF2195AEE65FF3999051BF6AEAD780D326DBF301DB984C036312CCF61631EB05015E528E0A9" created="2013-10-01 16:29:20"/>
	<pen display_id="AYE-ASW-KBA-EH" serialnumber="2594160247175" serialnumber_hex="25C00000187" firmware_version="1.5" pen_type="Vector" created="2013-10-01 16:29:20" />
	<pen display_id="AYE-ASW-KBA-EH" serialnumber="2594160247175" serialnumber_hex="25C00000187" firmware_version="1.5" pen_type="Vector" created="2013-10-01 16:29:20" />
	<pen display_id="AYE-ASW-AED-HB" serialnumber="2594172882907" serialnumber_hex="25C00C0CFDB" firmware_version="1.5" pen_type="Vector" created="2013-11-06 10:22:47" />
	<pen display_id="AYE-ASX-CM4-KB" serialnumber="2594172911908" serialnumber_hex="25C00C14124" firmware_version="1.5" pen_type="Vector" created="2013-11-06 10:22:47" />
</dataset>
<!-- 
pen_id for AYE-ASW-ABK-EH:  2524791
 -->
