=== erikhaugen/web/livescribe/lstokenservice/src/test/resources/data/dtd/registered_device.dtd
<!ELEMENT dataset (registered_device*)>

<!ELEMENT registered_device EMPTY>
<!-- Must include 'registered_device_id' column to workaround 'bug' in DbUnit when
	 deleting DataSet records from database. -->
<!ATTLIST registered_device registered_device_id	CDATA #IMPLIED>
<!ATTLIST registered_device user_id					CDATA #IMPLIED>
<!ATTLIST registered_device device_id				CDATA #IMPLIED>
<!ATTLIST registered_device device_serial_number	CDATA #IMPLIED>
<!ATTLIST registered_device device_type				CDATA #IMPLIED>
<!ATTLIST registered_device reg_code				CDATA #IMPLIED>
<!ATTLIST registered_device reg_token				CDATA #IMPLIED>
<!ATTLIST registered_device complete				CDATA #IMPLIED>
<!ATTLIST registered_device completed_date			CDATA #IMPLIED>
<!ATTLIST registered_device created					CDATA #IMPLIED>
<!ATTLIST registered_device last_modified			CDATA #IMPLIED>
<!ATTLIST registered_device last_modified_by		CDATA #IMPLIED>

=== erikhaugen/web/livescribe/lstokenservice/src/test/resources/data/setup/registered_device.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset SYSTEM "../dtd/registered_device.dtd">
<dataset>
	<registered_device registered_device_id="10000" user_id="[null]" device_id="66" device_serial_number="2594160246848" device_type="Wi-Fi" reg_code="XKY69H" reg_token="[null]" complete="0" completed_date="1970-01-01" created="2012-02-14" last_modified="2012-02-14" last_modified_by="KFM" />
	<registered_device registered_device_id="10001" user_id="[null]" device_id="151" device_serial_number="2594160246933" device_type="Wi-Fi" reg_code="KJD7F2" reg_token="[null]" complete="0" completed_date="1970-01-01" created="2012-02-28" last_modified="2012-02-28" last_modified_by="KFM" />
	<registered_device registered_device_id="10002" user_id="[null]" device_id="20000" device_serial_number="7823948029286" device_type="Wi-Fi" reg_code="USR39P" reg_token="[null]" complete="0" completed_date="1970-01-01" created="2012-02-29" last_modified="2012-02-29" last_modified_by="KFM" />
	<registered_device registered_device_id="10003" user_id="[null]" device_id="100000" device_serial_number="7823948029349" device_type="Wi-Fi" reg_code="PEQRYB" reg_token="[null]" complete="0" completed_date="1970-01-01" created="2012-03-01 22:01:00" last_modified="2012-03-01 15:00:00" last_modified_by="KFM" />
	<registered_device registered_device_id="10004" user_id="[null]" device_id="100001" device_serial_number="7823948029946" device_type="Wi-Fi" reg_code="BT729V" reg_token="[null]" complete="0" completed_date="1970-01-01" created="2012-03-01 22:02:00" last_modified="2012-03-01 15:00:00" last_modified_by="KFM" />
	<registered_device registered_device_id="10005" user_id="[null]" device_id="100002" device_serial_number="7823948029556" device_type="Wi-Fi" reg_code="CYP9WE" reg_token="[null]" complete="0" completed_date="1970-01-01" created="2012-03-01 22:03:00" last_modified="2012-03-01 15:00:00" last_modified_by="KFM" />
	<registered_device registered_device_id="10006" user_id="[null]" device_id="100003" device_serial_number="7823948029229" device_type="Wi-Fi" reg_code="AGU2MM" reg_token="[null]" complete="0" completed_date="1970-01-01" created="2012-03-01 22:04:00" last_modified="2012-03-01 15:00:00" last_modified_by="KFM" />
	<registered_device registered_device_id="10007" user_id="[null]" device_id="100004" device_serial_number="7823948029878" device_type="Wi-Fi" reg_code="23NTV9" reg_token="[null]" complete="0" completed_date="1970-01-01" created="2012-03-01 22:05:00" last_modified="2012-03-01 15:00:00" last_modified_by="KFM" />
	<registered_device registered_device_id="10008" user_id="[null]" device_id="100005" device_serial_number="7823948029347" device_type="Wi-Fi" reg_code="FJVW9P" reg_token="[null]" complete="0" completed_date="1970-01-01" created="2012-03-01 22:06:00" last_modified="2012-03-01 15:00:00" last_modified_by="KFM" />
	<registered_device registered_device_id="10009" user_id="[null]" device_id="100006" device_serial_number="7823948029609" device_type="Wi-Fi" reg_code="QWETT6" reg_token="[null]" complete="0" completed_date="1970-01-01" created="2012-03-01 22:07:00" last_modified="2012-03-01 15:00:00" last_modified_by="KFM" />
	<registered_device registered_device_id="10010" user_id="[null]" device_id="100007" device_serial_number="7823948029141" device_type="Wi-Fi" reg_code="G8Y9SW" reg_token="[null]" complete="0" completed_date="1970-01-01" created="2012-03-01 22:08:00" last_modified="2012-03-01 15:52:00" last_modified_by="KFM" />
</dataset>
